[package]
name = "schema-registry"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tracing.workspace = true
deltaforge-core = {path = "../deltaforge-core"}
