[book]
title = "DeltaForge CDC Framework - User Guide"
authors = ["Vahid Negahdari"]
language = "en"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["css/custom.css"]