[book]
title = "DeltaForge CDC Framework - User Guide"
authors = ["Vahid Negahdari"]
language = "en"
description = "Documentation for DeltaForge, a modular change data capture (CDC) and streaming micro-framework in Rust"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/vnvo/deltaforge"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/vnvo/deltaforge/edit/main/docs/src/{path}"
site-url = "/deltaforge/"
no-section-label = true

[output.html.search]
enable = true
limit-results = 20

[output.html.fold]
enable = true
level = 1

