[book]
authors = ["DeltaForge Contributors"]
language = "en"
multilingual = false
src = "src"
title = "DeltaForge User Guide"

description = "Change Data Capture pipelines with DeltaForge: configuration, runtime behavior, and deployment tips."

[build]
default-theme = "light"

[output.html]
additional-css = []
git-repository-url = "https://github.com/vnvo/deltaforge"
git-repository-icon = "fa-github"
additional-js = []

[preprocessor.links]
