[book]
title = "DeltaForge CDC Framework - User Guide"
authors = ["Vahid Negahdari"]
language = "en"
description = "DeltaForge is an efficient rust-based Change Data Capture (CDC) framework for streaming MySQL binlog and Postgres logical replication changes into Kafka and Redis with config-driven pipelines and inline Javascript processing."

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/vnvo/deltaforge"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/vnvo/deltaforge/edit/main/docs/src/{path}"
site-url = "https://vnvo.github.io/deltaforge/"
no-section-label = true

[output.html.search]
enable = true
limit-results = 20

[output.html.fold]
enable = true
level = 1

